services:
  cms:
    container_name: devmat-cms-${BUILD_CONFIG}
    build:
      context: .
      dockerfile: Dockerfile.${BUILD_CONFIG}
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      BUILD_CONFIG: ${BUILD_CONFIG}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
    # command: sleep infinity
    volumes:
      - ./config:/opt/app/config
      - ./database:/opt/app/database
      - ./public:/opt/app/public
      - ./src:/opt/app/src
      - ./types:/opt/app/types
      - ./exports:/opt/app/exports
    expose:
      - ${PORT}
    # ports:
    #   - ${PORT}:${PORT}
    networks:
      common_network:
        ipv4_address: 172.18.0.23

networks:
  common_network:
    external: true