services:
  app:
    container_name: devmat-ui-production
    build: .
    expose:
      - 3030
    # ports:
    #   - 3030:3030
    networks:
      common_network:
        ipv4_address: 172.18.0.22
    # command: sleep infinity

  middleman:
    container_name: middleman-to-strapi
    build: apps/middleman-to-strapi
    # ports:
    #   - 5151:5151
    expose:
      - 5151
    networks:
      common_network:
        ipv4_address: 172.18.0.25

networks:
  common_network:
    external: true